Curiosity26\AclHelperBundle\Entity\AclClass:
    table: "acl_classes"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        classType:
            name: class_type
            type: string
            length: 200
            unique: true