Curiosity26\AclHelperBundle\Entity\Entry:
    table: "acl_entries"
    type: entity
    read-only: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        classId:
            name: class_id
            type: integer
            options:
                unsigned: true
        objectIdentityId:
            name: object_identity_id
            type: integer
            options:
                unsigned: true
        securityIdentityId:
            name: security_identity_id
            type: integer
            options:
                unsigned: true
        fieldName:
            name: field_name
            type: string
            length: 50
        aceOrder:
            name: ace_order
            type: smallint
            options:
                unsigned: true
        mask:
            type: integer
        granting:
            type: boolean
        grantingStrategy:
            name: granting_strategy
            type: string
            length: 30
        auditSuccess:
            name: audit_success
            type: boolean
        auditFailure:
            name: audit_failure
            type: boolean