AE\AclHelperBundle\Entity\Entry:
    table: "acl_entries"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        fieldName:
            type: string
            length: 50
            nullable: true
        aceOrder:
            type: smallint
            default: 0
            options:
                unsigned: true
        mask:
            type: integer
        granting:
            type: boolean
        grantingStrategy:
            name: granting_strategy
            type: string
            length: 30
            default: 'all'
        auditSuccess:
            name: audit_success
            type: boolean
        auditFailure:
            name: audit_failure
            type: boolean
    manyToOne:
        class:
            targetEntity: 'AE\AclHelperBundle\Entity\AclClass'
            cascade: ["persist"]
            joinColumns:
                class_id:
                    nullable: false
                    options:
                        unsigned: true
            nullable: false
        objectIdentity:
            targetEntity: 'AE\AclHelperBundle\Entity\ObjectIdentity'
            casade: ['persist']
            joinColumns:
                object_identity_id:
                    options:
                        unsigned: true
        securityIdentity:
            targetEntity: 'AE\AclHelperBundle\Entity\SecurityIdentity'
            cascade: ["persist"]
            joinColumns:
                security_identity_id:
                    nullable: false
                    options:
                        unsigned: true
    uniqueConstraints:
        entry_idx:
            columns: [class_id, object_identity_id, field_name, ace_order]
    indexes:
        entry_indexes:
            columns: [class_id, object_identity_id, security_identity_id]