Curiosity26\AclHelperBundle\Entity\Entry:
    table: "acl_entries"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        fieldName:
            type: string
            length: 50
            nullable: true
        aceOrder:
            type: smallint
            default: 0
            options:
                unsigned: true
        mask:
            type: integer
        granting:
            type: boolean
        grantingStrategy:
            name: granting_strategy
            type: string
            length: 30
            default: 'all'
        auditSuccess:
            name: audit_success
            type: boolean
        auditFailure:
            name: audit_failure
            type: boolean
    manyToOne:
        class:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\AclClass'
            cascade: ["persist"]
        objectIdentity:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\ObjectIdentity'
            casade: ['persist']
        securityIdentity:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\SecurityIdentity'
            cascade: ["persist"]
