Curiosity26\AclHelperBundle\Entity\ObjectIdentity:
    table: "acl_object_identities"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        parentObjectIdentity:
            column: parent_object_identity_id
            type: integer
            nullable: true
            options:
                unsigned: true
        objectIdentifier:
            type: string
            length: 100
        entriesInheriting:
            type: boolean
    manyToOne:
        class:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\AclClass'
            cascade: ["persist"]
    manyToMany:
        parent:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\ObjectIdentity'
            mappedBy: ancestor
        ancestor:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\ObjectIdentity'
            inversedBy: parentObjectIdentity
            joinTable:
                name: acl_object_identity_ancestors
                inversedJoinColumns:
                    object_identity_id:
                        referencedColumnName: id
                joinColumns:
                    ancestor_id:
                        referencedColumnName: id

