Curiosity26\AclHelperBundle\Entity\ObjectIdentity:
    table: "acl_object_identities"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        objectIdentifier:
            type: string
            length: 100
            nullable: false
        entriesInheriting:
            type: boolean
    manyToOne:
        class:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\AclClass'
            cascade: ["persist"]
            joinColumns:
                class_id:
                    nullable: false
                    options:
                        unsigned: true
        parentObjectIdentity:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\ObjectIdentity'
            joinColumns:
                parent_object_identity_id:
                    options:
                        unsigned: true
    manyToMany:
        ancestor:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\ObjectIdentity'
            joinTable:
                name: acl_object_identity_ancestors
                joinColumns:
                    object_identity_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    ancestor_id:
                        referencedColumnName: id
    uniqueConstraints:
        class_identifier_idx:
            columns: [class_id, object_identifier]
