Curiosity26\AclHelperBundle\Entity\ObjectIdentity:
    table: "acl_object_identities"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        parentObjectIdentity:
            column: parent_object_identity_id
            type: integer
            nullable: true
            options:
                unsigned: true
        objectIdentifier:
            type: string
            length: 100
        entriesInheriting:
            type: boolean
    manyToOne:
        class:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\AclClass'
            cascade: ["persist"]
    manyToMany:
        ancestor:
            targetEntity: 'Curiosity26\AclHelperBundle\Entity\ObjectIdentity'
            joinTable:
                name: acl_object_identity_ancestors
                joinColumns:
                    object_identity_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    ancestor_id:
                        referencedColumnName: id
    uniqueConstraints:
        class_identifier_idx:
            columns: [class_id, object_identifier]
