Curiosity26\AclHelperBundle\Entity\ObjectIdentity:
    table: "acl_object_identities"
    type: entity
    read-only: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        parentObjectIdentityId:
            name: parent_object_identity_id
            type: integer
            options:
                unsigned: true
        classId:
            name: class_id
            type: integer
            options:
                unsigned: true
        objectIdentifier:
            name: object_identifier
            type: string
            length: 100
        entriesInheriting:
            name: entries_inheriting
            type: boolean