Curiosity26\AclHelperBundle\Entity\SecurityIdentity:
    table: "acl_security_identities"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        identifier:
            type: string
            length: 200
        username:
            type: boolean