AE\AclHelperBundle\Entity\SecurityIdentity:
    table: "acl_security_identities"
    type: entity
    readOnly: true
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        identifier:
            type: string
            length: 200
            nullable: false
        username:
            type: boolean
    uniqueConstraints:
        identifier_username_idx:
            columns: [identifier, username]