services:
    Curiosity26\AclHelperBundle\QueryBuilder\AclHelperQueryBuilder:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $roleHierarchy: '@?security.role_hierarchy'
    Curiosity26\AclHelperBundle\Helper\AclHelper:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
            $queryBuilder: '@Curiosity26\AclHelperBundle\QueryBuilder\AclHelperQueryBuilder'
            $provider: '@security.acl.provider'
        calls:
             - ['setLogger', ['@?Psr\Log\LoggerInterface']]
        public: true
    security.acl.dbal.schema_listener:
        class: 'Curiosity26\AclHelperBundle\EventListener\AclSchemaListener'
        arguments: ['@security.acl.dbal.schema']
        tags:
            - {name: 'doctrine.event_listener', connection: 'default', event: 'postGenerateSchema', lazy: true}