services:
    Curiosity26\AclHelperBundle\QueryBuilder\AclHelperQueryBuilder:
        $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        $roleHierarchy: '@?security.role_hierarchy'
    Curiosity26\AclHelperBundle\Helper\AclHelper:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
            $queryBuilder: '@Curiosity26\AclHelperBundle\QueryBuilder\AclHelperQueryBuilder'
            $provider: '@security.acl.provider'
        public: true